### ISSUE TITLE
Vote totals sometimes confusing?

### ISSUE THREAD

**Issue by MattConrad** [damonblack/rcv-sim#10]
If you run the Arglebargle election from Firebase cloud, you'll see that Round 1 reports 15 votes, while Round 2 reports 14 votes. It looks like a vote is getting lost.

I dug into this and I believe that one of the votes just doesn't have a second place choice (though it does seem to have a third place choice) so the change in vote count is correct . . . but it's rather confusing.

Possibly more explanation of this scenario (possibly conditional on it actually happening) would address it, or maybe it would be simplest to just drop the vote totals entirely.

**Comment by damonblack** [comment]
Add #21 to address this.
