### ISSUE TITLE
Cleanup Navigation

### ISSUE THREAD

**Issue by damonblack** [damonblack/rcv-sim#12]
At a minimum a logged in user should be able to go back and forth between the Monitor, Home and Vote screens without using the back button or hacking the url.

...

Make it something nice.

**Comment by damonblack** [comment]
This can be accomplished with `history.push('/path')` - the history is injected into the props by withRouter, along with match and location. But the more typical way to do navigation is with the Link component which hooks this up, and has a 'to' for stipulating the path.

This is further abstracted by MUI's wrapper components, which will accept a Link in their props to effect the navigation. See the Previous and Next buttons in Monitor.js for examples.

**Comment by MattConrad** [comment]
Closing, since it's done (?)
