### ISSUE TITLE
With Firebase, do we need to worry about the amount of stored data?

### ISSUE THREAD

**Issue by damonblack** [damonblack/rcv-sim#2]
I haven't yet looked seriously at the pricing structure for Firebase or Firebase Hosting, but at some point the free isn't so free any more. Should we worry about clearing out old data, either for performance reasons or service usage?

**Comment by MattConrad** [comment]
So you've probably seen this: https://firebase.google.com/pricing/

Quite a bit of room in the free tier, but the $25/month tier would give some wiggle room and isn't too expensive.

Do note this unhappy story: https://startupsventurecapital.com/firebase-costs-increased-by-7-000-81dc0a27271d which I think is unlikely to be our case, but something to keep in mind. If we (by which I mean RCV CO) starts paying for Firebase, they'll want some way to be sure their costs aren't skyrocketing while they're not paying attention.

Hmm, here's another scary one: https://medium.com/icelytics/firebase-database-mysterious-billing-6d06f3fe4d2e . I'm not sure I'd want Firebase to have my CC #, honestly. Seems easy to get into a place where your bill is spiking and you don't know why.

My current feeling is, let's try to figure out how to keep resource usage within the free tier. So, to answer the original question, YES. How to do that best, I have the proof of, but it will not fit within the comment length limit, so I'll have to add it some other time.

**Comment by damonblack** [comment]
Thanks, ferMatt. :)

Yeah. That sounds about right. We probably need to run some kind of function that closes elections after a certain maximum of votes.
