### ISSUE TITLE
Figure out how to limit the length of user owned collections.

### ISSUE THREAD

**Issue by damonblack** [damonblack/rcv-sim#3]
So far, the only really annoying thing about Firebase is that its database rules file, which ends up doing most of the heavy lifting in your data design, don't have the capacity to limit, or even report, the length of a collection.

The workaround mentioned the most consistently in discussions involves a cloud function, triggered by updates to the db, that impose the limits - by deleting them after the fact. :( 

Maybe I'm worried about nothing and the data will be a drop in the bucket, er cloud-bucket. If that's so, we can simply tag stuff as 'deleted' and filter it from users.

**Comment by MattConrad** [comment]
I looked at this some today. I don't see any options other than deleting after the fact.

We can add a `created` prop to `elections` elements, set it to Date.now(), and delete old elections (and related children) after a certain amount of time. This is a discussion on doing this: https://stackoverflow.com/questions/32004582/delete-firebase-data-older-than-2-hours

We could start with a delete window of 2 weeks and dial it in tighter as needed.

We can probably trigger this on a schedule using Zapier.

We wouldn't necessarily need a cloud function, although a cloud function may be the easiest way to subvert the app db access rules and do a global delete. We could make the db rules hairier so certain users have global write permissions. Or we could write a brand new app with firebase admin.

I'm guessing cloud function is the simplest approach, although people say they're not much fun to debug. I'll look at this more.
