### ISSUE TITLE
Voting doesn't handle ties correctly:

### ISSUE THREAD

**Issue by MattConrad** [damonblack/rcv-sim#8]
There are a couple of different elections in the cloud that demo this.

If multiple candidates are equally losery, the first one noticed is the only one considered a loser.

**Comment by damonblack** [comment]
Yeah. There are several minor issues with the calculations. I'm working on some automated tests now that should facilitate a proper rewrite of that ungodly mess.

**Comment by damonblack** [comment]
I need to contact the FairVote folks and find out what they want to do with ties. It think it's either randomly decided which one will be the loser for the round, or defers to their second-place vote total.

**Comment by MattConrad** [comment]
> It think it's either randomly decided which one will be the loser for the round

wat
